### ISSUE TITLE
Add typeset defaults?

### ISSUE THREAD

**Issue by madeleineostoja** [heybokeh/pollen#42]
Opinionated pairings of line heights with the modular font scale for sans and serif font families.

- Applies to: `font`
- Property group: `sans-` and `serif-`

Values eg:

```css
:root {
	--sans-0: var(--scale-0)/1.5, var(--font-sans);
}
```

Usage:

```css
.paragraph {
  font: var(--sans-0);
}
```
