### ISSUE TITLE
Support for wider color gamuts

### ISSUE THREAD

**Issue by kevmodrome** [heybokeh/pollen#62]
Safari supports eye-popping colors using the the `color()` function. I wonder if it'd be neat to maybe add support for this with graceful fallback to regular old hex/hsl.

I have successfully used this on the Svelte Summit website and I think the result is pretty nice. You can see the difference by visiting on Chrome vs Safari.

It would be as simple as figuring out what colors that would be nice to have and then just adding support via something like this (example taken from the [WebKit explainer page](https://webkit.org/blog/10042/wide-gamut-color-in-css-with-display-p3/)):
```css
:root {
    --bright-green: rgb(0, 255, 0);
}

/* Display-P3 color, when supported. */
@supports (color: color(display-p3 1 1 1)) {
    :root {
        --bright-green: color(display-p3 0 1 0);
    }
}
```

Another idea is to support the `lch()` and `lab()` functions.

[Here's a site](https://webkit.org/blog-files/color-gamut/comparison.html) where you can compare between the two - you need to use Safar on a Mac or iPhone to see differences.
